export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const SORT = 'SORT';
export const LIST_ALL = 'LIST_ALL';
export const LOGIN = 'LOGIN';
export const OPEN_PREVIEW_TEMPLATE='OPEN_PREVIEW_TEMPLATE';
export const CLOSE_PREVIEW_TEMPLATE='CLOSE_PREVIEW_TEMPLATE';